name: hibernate-sample

services:
  database:
    container_name: postgres
    image: postgres:17.2
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
volumes:
  postgres-data:
